#spring.application.name=springboot-blog-rest-api
#spring.datasource.url=jdbc:postgresql://localhost:5332/myblog
#spring.datasource.username=admin123
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto=update

# Hibernate properties
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

# App properties
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app-jqt-expiration-milliseconds=604800000

spring.profiles.active=docker